version: '3.8'
services:
  django:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_USER=mydatabaseuser
      - DB_PASSWORD=mypassword
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=mydatabaseuser
      - MYSQL_PASSWORD=mypassword
      - MYSQL_ROOT_PASSWORD=mypassword
    volumes:
      - ./docker_data/mysql_data:/var/lib/mysql
  redis:
    image: redis:latest
    volumes:
      - ./docker_data/redis_data:/data
  celery:
    build: .
    command: celery -A finance_report worker --loglevel=info
    volumes:
      - .:/usr/src/code
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_USER=mydatabaseuser
      - DB_PASSWORD=mypassword
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
